name = "NISTStatisticalReferenceData"
uuid = "682effc9-3ac9-44b4-a18e-4cb901ae264e"
authors = ["joshday <emailjoshday@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
